

import React, { createContext, useContext, useState } from "react";

const translations = {


  en: {
    settings_title: "Settings",
    settings_subtitle: "Manage your account preferences and configurations",
    nav_label: "Navigation",
    your_role: "Your Role",

    full_platform_access: "Full platform access",
    company_management: "Company management",
    campaign_management: "Campaign management",
    read_only_access: "Read-only access",

    tab_profile: "Profile",
    tab_security: "Security",
    tab_notifications: "Notifications",
    tab_team: "Team",
    tab_email: "Email Service",
    tab_integrations: "Integrations",
    tab_billing: "Billing",
    tab_system: "System",

    personal_info: "Personal Information",
    full_name: "Full Name",
    email_address: "Email Address",
    company_name: "Company Name",
    phone_number: "Phone Number",
    bio_about: "Bio / About",
    preferences: "Preferences",
    timezone: "Timezone",
    language: "Language",
    save_profile: "Save Profile",
    saving: "Saving...",
    saved: "Saved!",
    name_placeholder: "Your full name",
    email_placeholder: "you@example.com",
    company_placeholder: "Your company name",
    phone_placeholder: "+91 98765 43210",
    bio_placeholder: "Write a short bio about yourself...",

    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    change_password_btn: "Update Password",
    changing: "Updating...",
    password_placeholder: "Enter password",
    passwords_no_match: "Passwords do not match",
    pwd_weak: "Weak",
    pwd_fair: "Fair",
    pwd_good: "Good",
    pwd_strong: "Strong",
    two_factor: "Two-Factor Authentication",
    two_factor_desc: "Add an extra layer of security to your account",
    two_fa_enabled: "Two-factor authentication is enabled on your account.",
    active_sessions: "Active Sessions",
    revoke_all: "Revoke All",
    revoke: "Revoke",
    current_session: "Current",

    email_notif_group: "Email Notifications",
    sms_notif_group: "SMS Notifications",
    inapp_notif_group: "In-App Notifications",
    notif_campaign_updates: "Campaign Updates",
    notif_campaign_desc: "When campaigns are sent or completed",
    notif_weekly_reports: "Weekly Reports",
    notif_weekly_desc: "Performance summary every Monday",
    notif_billing_alerts: "Billing Alerts",
    notif_billing_desc: "Invoices, renewals, and payment issues",
    notif_team_activity: "Team Activity",
    notif_team_desc: "When team members take actions",
    notif_otp: "OTP & Verification",
    notif_otp_desc: "Login and security verification codes",
    notif_critical: "Critical Alerts Only",
    notif_critical_desc: "System downtime or urgent issues",
    notif_campaign_status: "Campaign Status",
    notif_campaign_status_desc: "Live updates on sending progress",
    notif_team_updates: "Team Updates",
    notif_team_updates_desc: "Invites and role changes",
    notif_system_notices: "System Notices",
    notif_system_desc: "Maintenance and platform updates",
    digest_frequency: "Notification Digest",
    freq_real_time: "Real-Time",
    freq_daily: "Daily",
    freq_weekly: "Weekly",
    freq_never: "Never",

    team_members: "Team Members",
    members_in_team: "members in your team",
    search_members: "Search members...",
    invite: "Invite",
    invite_title: "Invite Team Member",
    invite_email: "Email Address",
    invite_email_placeholder: "colleague@company.com",
    invite_role: "Assign Role",
    send_invite: "Send Invite",
    cancel: "Cancel",
    total: "Total",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    member_col: "Member",
    role_col: "Role",
    status_col: "Status",
    joined_col: "Joined",
    actions_col: "Actions",
    edit_btn: "Edit",
    remove_btn: "Remove",

    email_provider: "Email Provider",
    configuration: "Configuration",
    api_key: "API Key",
    from_email: "From Email",
    from_name: "From Name",
    reply_to: "Reply-To Email",
    daily_limit: "Daily Send Limit",
    hourly_limit: "Hourly Send Limit",
    test_email: "Test Connection",
    testing: "Testing...",
    test_success: "Connection successful! Email service is working.",
    save_config: "Save Configuration",

    integrations_active: "integrations active",
    integrations_subtitle: "Connect your favourite tools and services",
    connected_badge: "Connected",
    connect: "Connect",
    disconnect: "Disconnect",

    current_plan: "Current Plan",
    renews_on: "Renews on April 1, 2026",
    usage_this_month: "Usage This Month",
    emails_sent: "Emails Sent",
    contacts: "Contacts",
    team_members_usage: "Team Members",
    used: "used",
    available_plans: "Available Plans",
    most_popular: "Most Popular",
    current_plan_btn: "Current Plan",
    contact_sales: "Contact Sales",
    upgrade: "Upgrade",
    invoice_history: "Invoice History",
    pdf: "PDF",

    super_admin_only: "Super Admin Only",
    system_warning: "Changes here affect the entire platform. Proceed with caution.",
    platform_controls: "Platform Controls",
    platform_config: "Platform Configuration",
    on: "ON",
    off: "OFF",
    save_system: "Save System Settings",
  },


  mr: {
    settings_title: "सेटिंग्स",
    settings_subtitle: "तुमच्या खाते प्राधान्ये आणि कॉन्फिगरेशन व्यवस्थापित करा",
    nav_label: "नेव्हिगेशन",
    your_role: "तुमची भूमिका",

    full_platform_access: "पूर्ण प्लॅटफॉर्म प्रवेश",
    company_management: "कंपनी व्यवस्थापन",
    campaign_management: "कॅम्पेन व्यवस्थापन",
    read_only_access: "फक्त वाचण्याचा प्रवेश",

    tab_profile: "प्रोफाइल",
    tab_security: "सुरक्षा",
    tab_notifications: "सूचना",
    tab_team: "टीम",
    tab_email: "ईमेल सेवा",
    tab_integrations: "इंटिग्रेशन",
    tab_billing: "बिलिंग",
    tab_system: "सिस्टम",

    personal_info: "वैयक्तिक माहिती",
    full_name: "पूर्ण नाव",
    email_address: "ईमेल पत्ता",
    company_name: "कंपनीचे नाव",
    phone_number: "फोन नंबर",
    bio_about: "बायो / परिचय",
    preferences: "प्राधान्ये",
    timezone: "टाइमझोन",
    language: "भाषा",
    save_profile: "प्रोफाइल जतन करा",
    saving: "जतन होत आहे...",
    saved: "जतन झाले!",
    name_placeholder: "तुमचे पूर्ण नाव",
    email_placeholder: "you@example.com",
    company_placeholder: "तुमच्या कंपनीचे नाव",
    phone_placeholder: "+91 98765 43210",
    bio_placeholder: "तुमच्याबद्दल थोडक्यात लिहा...",

    change_password: "पासवर्ड बदला",
    current_password: "सध्याचा पासवर्ड",
    new_password: "नवीन पासवर्ड",
    confirm_password: "पासवर्ड पुष्टी करा",
    change_password_btn: "पासवर्ड अपडेट करा",
    changing: "अपडेट होत आहे...",
    password_placeholder: "पासवर्ड टाका",
    passwords_no_match: "पासवर्ड जुळत नाहीत",
    pwd_weak: "कमकुवत",
    pwd_fair: "ठीक",
    pwd_good: "चांगला",
    pwd_strong: "मजबूत",
    two_factor: "द्वि-घटक प्रमाणीकरण",
    two_factor_desc: "तुमच्या खात्यात अतिरिक्त सुरक्षा स्तर जोडा",
    two_fa_enabled: "द्वि-घटक प्रमाणीकरण सक्रिय आहे.",
    active_sessions: "सक्रिय सत्रे",
    revoke_all: "सर्व रद्द करा",
    revoke: "रद्द करा",
    current_session: "सध्याचे",

    email_notif_group: "ईमेल सूचना",
    sms_notif_group: "SMS सूचना",
    inapp_notif_group: "अॅप सूचना",
    notif_campaign_updates: "कॅम्पेन अपडेट",
    notif_campaign_desc: "कॅम्पेन पाठवले/पूर्ण झाल्यावर",
    notif_weekly_reports: "साप्ताहिक अहवाल",
    notif_weekly_desc: "प्रत्येक सोमवारी कामगिरी सारांश",
    notif_billing_alerts: "बिलिंग अलर्ट",
    notif_billing_desc: "इनव्हॉइस, नूतनीकरण, आणि देयक समस्या",
    notif_team_activity: "टीम क्रियाकलाप",
    notif_team_desc: "टीम सदस्यांनी कृती केल्यावर",
    notif_otp: "OTP आणि पडताळणी",
    notif_otp_desc: "लॉगिन आणि सुरक्षा कोड",
    notif_critical: "फक्त गंभीर अलर्ट",
    notif_critical_desc: "सिस्टम डाउनटाइम किंवा तातडीच्या समस्या",
    notif_campaign_status: "कॅम्पेन स्थिती",
    notif_campaign_status_desc: "पाठवण्याची प्रगती",
    notif_team_updates: "टीम अपडेट",
    notif_team_updates_desc: "आमंत्रणे आणि भूमिका बदल",
    notif_system_notices: "सिस्टम सूचना",
    notif_system_desc: "देखभाल आणि प्लॅटफॉर्म अपडेट",
    digest_frequency: "सूचना डायजेस्ट",
    freq_real_time: "रियल-टाइम",
    freq_daily: "दैनिक",
    freq_weekly: "साप्ताहिक",
    freq_never: "कधीही नाही",

    team_members: "टीम सदस्य",
    members_in_team: "सदस्य तुमच्या टीममध्ये",
    search_members: "सदस्य शोधा...",
    invite: "आमंत्रित करा",
    invite_title: "टीम सदस्याला आमंत्रित करा",
    invite_email: "ईमेल पत्ता",
    invite_email_placeholder: "colleague@company.com",
    invite_role: "भूमिका नियुक्त करा",
    send_invite: "आमंत्रण पाठवा",
    cancel: "रद्द करा",
    total: "एकूण",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    pending: "प्रलंबित",
    member_col: "सदस्य",
    role_col: "भूमिका",
    status_col: "स्थिती",
    joined_col: "सामील झाले",
    actions_col: "क्रिया",
    edit_btn: "संपादित करा",
    remove_btn: "काढा",

    email_provider: "ईमेल प्रदाता",
    configuration: "कॉन्फिगरेशन",
    api_key: "API की",
    from_email: "पाठवणाऱ्याचा ईमेल",
    from_name: "पाठवणाऱ्याचे नाव",
    reply_to: "रिप्लाय-टू ईमेल",
    daily_limit: "दैनिक पाठवण्याची मर्यादा",
    hourly_limit: "तासाची पाठवण्याची मर्यादा",
    test_email: "कनेक्शन तपासा",
    testing: "तपासत आहे...",
    test_success: "कनेक्शन यशस्वी! ईमेल सेवा कार्यरत आहे.",
    save_config: "कॉन्फिगरेशन जतन करा",

    integrations_active: "इंटिग्रेशन सक्रिय",
    integrations_subtitle: "तुमची आवडती टूल्स आणि सेवा कनेक्ट करा",
    connected_badge: "कनेक्ट आहे",
    connect: "कनेक्ट करा",
    disconnect: "डिस्कनेक्ट करा",

    current_plan: "सध्याची योजना",
    renews_on: "१ एप्रिल २०२६ रोजी नूतनीकरण होईल",
    usage_this_month: "या महिन्याचा वापर",
    emails_sent: "पाठवलेले ईमेल",
    contacts: "संपर्क",
    team_members_usage: "टीम सदस्य",
    used: "वापरले",
    available_plans: "उपलब्ध योजना",
    most_popular: "सर्वात लोकप्रिय",
    current_plan_btn: "सध्याची योजना",
    contact_sales: "विक्री संपर्क करा",
    upgrade: "अपग्रेड करा",
    invoice_history: "इनव्हॉइस इतिहास",
    pdf: "PDF",

    super_admin_only: "फक्त सुपर अॅडमिन",
    system_warning: "येथील बदल संपूर्ण प्लॅटफॉर्मवर परिणाम करतात. काळजीपूर्वक पुढे जा.",
    platform_controls: "प्लॅटफॉर्म नियंत्रणे",
    platform_config: "प्लॅटफॉर्म कॉन्फिगरेशन",
    on: "चालू",
    off: "बंद",
    save_system: "सिस्टम सेटिंग्स जतन करा",
  },


  hi: {
    settings_title: "सेटिंग्स",
    settings_subtitle: "अपने खाते की प्राथमिकताएं और कॉन्फ़िगरेशन प्रबंधित करें",
    nav_label: "नेविगेशन",
    your_role: "आपकी भूमिका",

    full_platform_access: "पूर्ण प्लेटफ़ॉर्म एक्सेस",
    company_management: "कंपनी प्रबंधन",
    campaign_management: "कैंपेन प्रबंधन",
    read_only_access: "केवल पढ़ने की पहुँच",

    tab_profile: "प्रोफ़ाइल",
    tab_security: "सुरक्षा",
    tab_notifications: "सूचनाएं",
    tab_team: "टीम",
    tab_email: "ईमेल सेवा",
    tab_integrations: "इंटीग्रेशन",
    tab_billing: "बिलिंग",
    tab_system: "सिस्टम",

    personal_info: "व्यक्तिगत जानकारी",
    full_name: "पूरा नाम",
    email_address: "ईमेल पता",
    company_name: "कंपनी का नाम",
    phone_number: "फ़ोन नंबर",
    bio_about: "बायो / परिचय",
    preferences: "प्राथमिकताएं",
    timezone: "टाइमज़ोन",
    language: "भाषा",
    save_profile: "प्रोफ़ाइल सेव करें",
    saving: "सेव हो रहा है...",
    saved: "सेव हो गया!",
    name_placeholder: "आपका पूरा नाम",
    email_placeholder: "you@example.com",
    company_placeholder: "आपकी कंपनी का नाम",
    phone_placeholder: "+91 98765 43210",
    bio_placeholder: "अपने बारे में लिखें...",

    change_password: "पासवर्ड बदलें",
    current_password: "वर्तमान पासवर्ड",
    new_password: "नया पासवर्ड",
    confirm_password: "पासवर्ड की पुष्टि करें",
    change_password_btn: "पासवर्ड अपडेट करें",
    changing: "अपडेट हो रहा है...",
    password_placeholder: "पासवर्ड दर्ज करें",
    passwords_no_match: "पासवर्ड मेल नहीं खाते",
    pwd_weak: "कमज़ोर",
    pwd_fair: "ठीक",
    pwd_good: "अच्छा",
    pwd_strong: "मज़बूत",
    two_factor: "द्वि-कारक प्रमाणीकरण",
    two_factor_desc: "अपने खाते में सुरक्षा की अतिरिक्त परत जोड़ें",
    two_fa_enabled: "द्वि-कारक प्रमाणीकरण सक्रिय है।",
    active_sessions: "सक्रिय सत्र",
    revoke_all: "सभी रद्द करें",
    revoke: "रद्द करें",
    current_session: "वर्तमान",

    email_notif_group: "ईमेल सूचनाएं",
    sms_notif_group: "SMS सूचनाएं",
    inapp_notif_group: "इन-ऐप सूचनाएं",
    notif_campaign_updates: "कैंपेन अपडेट",
    notif_campaign_desc: "कैंपेन भेजे/पूर्ण होने पर",
    notif_weekly_reports: "साप्ताहिक रिपोर्ट",
    notif_weekly_desc: "हर सोमवार प्रदर्शन सारांश",
    notif_billing_alerts: "बिलिंग अलर्ट",
    notif_billing_desc: "इनवॉइस, नवीनीकरण और भुगतान समस्याएं",
    notif_team_activity: "टीम गतिविधि",
    notif_team_desc: "जब टीम सदस्य कार्रवाई करें",
    notif_otp: "OTP और सत्यापन",
    notif_otp_desc: "लॉगिन और सुरक्षा कोड",
    notif_critical: "केवल गंभीर अलर्ट",
    notif_critical_desc: "सिस्टम डाउनटाइम या तत्काल समस्याएं",
    notif_campaign_status: "कैंपेन स्थिति",
    notif_campaign_status_desc: "भेजने की प्रगति",
    notif_team_updates: "टीम अपडेट",
    notif_team_updates_desc: "आमंत्रण और भूमिका परिवर्तन",
    notif_system_notices: "सिस्टम सूचनाएं",
    notif_system_desc: "रखरखाव और प्लेटफ़ॉर्म अपडेट",
    digest_frequency: "सूचना डाइजेस्ट",
    freq_real_time: "रियल-टाइम",
    freq_daily: "दैनिक",
    freq_weekly: "साप्ताहिक",
    freq_never: "कभी नहीं",

    team_members: "टीम सदस्य",
    members_in_team: "सदस्य आपकी टीम में",
    search_members: "सदस्य खोजें...",
    invite: "आमंत्रित करें",
    invite_title: "टीम सदस्य आमंत्रित करें",
    invite_email: "ईमेल पता",
    invite_email_placeholder: "colleague@company.com",
    invite_role: "भूमिका असाइन करें",
    send_invite: "आमंत्रण भेजें",
    cancel: "रद्द करें",
    total: "कुल",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    pending: "लंबित",
    member_col: "सदस्य",
    role_col: "भूमिका",
    status_col: "स्थिति",
    joined_col: "शामिल हुए",
    actions_col: "कार्रवाई",
    edit_btn: "संपादित करें",
    remove_btn: "हटाएं",

    email_provider: "ईमेल प्रदाता",
    configuration: "कॉन्फ़िगरेशन",
    api_key: "API कुंजी",
    from_email: "प्रेषक ईमेल",
    from_name: "प्रेषक का नाम",
    reply_to: "रिप्लाई-टू ईमेल",
    daily_limit: "दैनिक भेजने की सीमा",
    hourly_limit: "प्रति घंटे भेजने की सीमा",
    test_email: "कनेक्शन जांचें",
    testing: "जांच हो रही है...",
    test_success: "कनेक्शन सफल! ईमेल सेवा काम कर रही है।",
    save_config: "कॉन्फ़िगरेशन सेव करें",

    integrations_active: "इंटीग्रेशन सक्रिय",
    integrations_subtitle: "अपने पसंदीदा टूल्स और सेवाएं कनेक्ट करें",
    connected_badge: "कनेक्टेड",
    connect: "कनेक्ट करें",
    disconnect: "डिस्कनेक्ट करें",

    current_plan: "वर्तमान योजना",
    renews_on: "1 अप्रैल 2026 को नवीनीकरण होगा",
    usage_this_month: "इस महीने का उपयोग",
    emails_sent: "भेजे गए ईमेल",
    contacts: "संपर्क",
    team_members_usage: "टीम सदस्य",
    used: "उपयोग किया",
    available_plans: "उपलब्ध योजनाएं",
    most_popular: "सबसे लोकप्रिय",
    current_plan_btn: "वर्तमान योजना",
    contact_sales: "बिक्री से संपर्क करें",
    upgrade: "अपग्रेड करें",
    invoice_history: "इनवॉइस इतिहास",
    pdf: "PDF",

    super_admin_only: "केवल सुपर एडमिन",
    system_warning: "यहाँ बदलाव पूरे प्लेटफ़ॉर्म को प्रभावित करते हैं। सावधानी से आगे बढ़ें।",
    platform_controls: "प्लेटफ़ॉर्म नियंत्रण",
    platform_config: "प्लेटफ़ॉर्म कॉन्फ़िगरेशन",
    on: "चालू",
    off: "बंद",
    save_system: "सिस्टम सेटिंग्स सेव करें",
  },


  gu: {
    settings_title: "સેટિંગ્સ",
    settings_subtitle: "તમારી એકાઉન્ટ પ્રાધાન્યતા અને ગોઠવણી સંચાલિત કરો",
    nav_label: "નેવિગેશન",
    your_role: "તમારી ભૂમિકા",

    full_platform_access: "સંપૂર્ણ પ્લેટફોર્મ ઍક્સેસ",
    company_management: "કંપની સંચાલન",
    campaign_management: "કેમ્પેઈન સંચાલન",
    read_only_access: "ફક્ત વાંચવાની ઍક્સેસ",

    tab_profile: "પ્રોફાઇલ",
    tab_security: "સુરક્ષા",
    tab_notifications: "સૂચનાઓ",
    tab_team: "ટીમ",
    tab_email: "ઈમેઈલ સેવા",
    tab_integrations: "ઈન્ટિગ્રેશન",
    tab_billing: "બિલિંગ",
    tab_system: "સિસ્ટમ",

    personal_info: "વ્યક્તિગત માહિતી",
    full_name: "પૂરું નામ",
    email_address: "ઈમેઈલ સરનામું",
    company_name: "કંપનીનું નામ",
    phone_number: "ફોન નંબર",
    bio_about: "બાયો / પરિચય",
    preferences: "પ્રાધાન્યતા",
    timezone: "ટાઈમઝોન",
    language: "ભાષા",
    save_profile: "પ્રોફાઇલ સાચવો",
    saving: "સાચવાઈ રહ્યું છે...",
    saved: "સાચવ્યું!",
    name_placeholder: "તમારું પૂરું નામ",
    email_placeholder: "you@example.com",
    company_placeholder: "તમારી કંપનીનું નામ",
    phone_placeholder: "+91 98765 43210",
    bio_placeholder: "તમારા વિશે થોડું લખો...",

    change_password: "પાસવર્ડ બદલો",
    current_password: "હાલનો પાસવર્ડ",
    new_password: "નવો પાસવર્ડ",
    confirm_password: "પાસવર્ડ પુષ્ટિ કરો",
    change_password_btn: "પાસવર્ડ અપડેટ કરો",
    changing: "અપડેટ થઈ રહ્યો છે...",
    password_placeholder: "પાસવર્ડ દાખલ કરો",
    passwords_no_match: "પાસવર્ડ મેળ ખાતા નથી",
    pwd_weak: "નબળો",
    pwd_fair: "ઠીક",
    pwd_good: "સારો",
    pwd_strong: "મજબૂત",
    two_factor: "Two-Factor Authentication",
    two_factor_desc: "તમારા ખાતામાં વધારાની સુરક્ષા ઉમેરો",
    two_fa_enabled: "Two-factor authentication સક્ષમ છે.",
    active_sessions: "સક્રિય સત્રો",
    revoke_all: "બધા રદ કરો",
    revoke: "રદ કરો",
    current_session: "હાલનું",

    email_notif_group: "ઈ-મેઈલ સૂચનાઓ",
    sms_notif_group: "SMS સૂચનાઓ",
    inapp_notif_group: "ઈન-એપ સૂચનાઓ",
    notif_campaign_updates: "કેમ્પેઈન અપડેટ",
    notif_campaign_desc: "કેમ્પેઈન મોકલ્યા/પૂર્ણ થયા ત્યારે",
    notif_weekly_reports: "સાપ્તાહિક અહેવાલ",
    notif_weekly_desc: "દર સોમવારે કામગીરી સારાંશ",
    notif_billing_alerts: "બિલિંગ ચેતવણી",
    notif_billing_desc: "ઇન્વૉઇસ, નવીકરણ અને ચુકવણી સમસ્યાઓ",
    notif_team_activity: "ટીમ પ્રવૃત્તિ",
    notif_team_desc: "ટીમ સભ્યો ક્રિયા કરે ત્યારે",
    notif_otp: "OTP અને ચકાસણી",
    notif_otp_desc: "લૉગિન અને સુરક્ષા કોડ",
    notif_critical: "ફક્ત ગંભીર ચેતવણી",
    notif_critical_desc: "સિસ્ટમ ડાઉનટાઇમ અથવા તાત્કાલિક સમસ્યાઓ",
    notif_campaign_status: "કેમ્પેઈન સ્થિતિ",
    notif_campaign_status_desc: "મોકલવાની પ્રગતિ",
    notif_team_updates: "ટીમ અપડેટ",
    notif_team_updates_desc: "આમંત્રણો અને ભૂમિકા ફેરફારો",
    notif_system_notices: "સિસ્ટમ સૂચનાઓ",
    notif_system_desc: "જાળવણી અને પ્લેટફોર્મ અપડેટ",
    digest_frequency: "સૂચના ડાઇજેસ્ટ",
    freq_real_time: "રિઅલ-ટાઇમ",
    freq_daily: "દૈનિક",
    freq_weekly: "સાપ્તાહિક",
    freq_never: "ક્યારેય નહીં",

    team_members: "ટીમ સભ્યો",
    members_in_team: "સભ્યો તમારી ટીમમાં",
    search_members: "સભ્ય શોધો...",
    invite: "આમંત્રિત કરો",
    invite_title: "ટીમ સભ્યને આમંત્રિત કરો",
    invite_email: "ઈ-મેઈલ સરનામું",
    invite_email_placeholder: "colleague@company.com",
    invite_role: "ભૂમિકા નિર્ધારિત કરો",
    send_invite: "આમંત્રણ મોકલો",
    cancel: "રદ કરો",
    total: "કુલ",
    active: "સક્રિય",
    inactive: "નિષ્ક્રિય",
    pending: "બાકી",
    member_col: "સભ્ય",
    role_col: "ભૂમિકા",
    status_col: "સ્થિતિ",
    joined_col: "જોડાયા",
    actions_col: "ક્રિયાઓ",
    edit_btn: "સંપાદિત કરો",
    remove_btn: "દૂર કરો",

    email_provider: "ઈ-મેઈલ પ્રદાતા",
    configuration: "ગોઠવણી",
    api_key: "API ચાવી",
    from_email: "મોકલનારનો ઈ-મેઈલ",
    from_name: "મોકલનારનું નામ",
    reply_to: "રિપ્લાય-ટુ ઈ-મેઈલ",
    daily_limit: "દૈનિક મોકલવાની મર્યાદા",
    hourly_limit: "કલાકદીઠ મોકલવાની મર્યાદા",
    test_email: "કનેક્શન ચકાસો",
    testing: "ચકાસી રહ્યા છીએ...",
    test_success: "કનેક્શન સફળ! ઈ-મેઈલ સેવા કાર્યરત છે.",
    save_config: "ગોઠવણી સાચવો",

    integrations_active: "ઈન્ટિગ્રેશન સક્રિય",
    integrations_subtitle: "તમારા મનપસંદ ટૂલ્સ અને સેવાઓ કનેક્ટ કરો",
    connected_badge: "કનેક્ટ",
    connect: "કનેક્ટ કરો",
    disconnect: "ડિસ્કનેક્ટ કરો",

    current_plan: "હાલની યોજના",
    renews_on: "1 એપ્રિલ 2026 ના રોજ નવીકરણ થશે",
    usage_this_month: "આ મહિને ઉપયોગ",
    emails_sent: "મોકલાયેલ ઈ-મેઈલ",
    contacts: "સંપર્કો",
    team_members_usage: "ટીમ સભ્યો",
    used: "ઉપયોગ",
    available_plans: "ઉપલબ્ધ યોજનાઓ",
    most_popular: "સૌથી લોકપ્રિય",
    current_plan_btn: "હાલની યોજના",
    contact_sales: "વેચાણ સંપર્ક",
    upgrade: "અપગ્રેડ",
    invoice_history: "ઇન્વૉઇસ ઇતિહાસ",
    pdf: "PDF",

    super_admin_only: "ફક્ત સુપર એડમિન",
    system_warning: "અહીં ફેરફારો સમગ્ર પ્લેટફોર્મ પર અસર કરે છે. સાવધાની સાથે આગળ વધો.",
    platform_controls: "પ્લેટફોર્મ નિયંત્રણો",
    platform_config: "પ્લેટફોર્મ ગોઠવણી",
    on: "ચાલુ",
    off: "બંધ",
    save_system: "સિસ્ટમ સેટિંગ્સ સાચવો",
  },


  ta: {
    settings_title: "அமைப்புகள்",
    settings_subtitle: "உங்கள் கணக்கு விருப்பங்கள் மற்றும் கட்டமைப்பை நிர்வகிக்கவும்",
    nav_label: "வழிசெலுத்தல்",
    your_role: "உங்கள் பாத்திரம்",

    full_platform_access: "முழு தளம் அணுகல்",
    company_management: "நிறுவன மேலாண்மை",
    campaign_management: "பிரச்சார மேலாண்மை",
    read_only_access: "படிக்க மட்டும் அணுகல்",

    tab_profile: "சுயவிவரம்",
    tab_security: "பாதுகாப்பு",
    tab_notifications: "அறிவிப்புகள்",
    tab_team: "குழு",
    tab_email: "மின்னஞ்சல் சேவை",
    tab_integrations: "ஒருங்கிணைப்பு",
    tab_billing: "வரவு செலவு",
    tab_system: "கணினி",

    personal_info: "தனிப்பட்ட தகவல்",
    full_name: "முழு பெயர்",
    email_address: "மின்னஞ்சல் முகவரி",
    company_name: "நிறுவன பெயர்",
    phone_number: "தொலைபேசி எண்",
    bio_about: "சுயவிவரம்",
    preferences: "விருப்பங்கள்",
    timezone: "நேர மண்டலம்",
    language: "மொழி",
    save_profile: "சுயவிவரம் சேமி",
    saving: "சேமிக்கிறது...",
    saved: "சேமிக்கப்பட்டது!",
    name_placeholder: "உங்கள் முழு பெயர்",
    email_placeholder: "you@example.com",
    company_placeholder: "உங்கள் நிறுவன பெயர்",
    phone_placeholder: "+91 98765 43210",
    bio_placeholder: "உங்களைப் பற்றி சிறிது எழுதுங்கள்...",

    change_password: "கடவுச்சொல் மாற்று",
    current_password: "தற்போதைய கடவுச்சொல்",
    new_password: "புதிய கடவுச்சொல்",
    confirm_password: "கடவுச்சொல் உறுதிப்படுத்து",
    change_password_btn: "கடவுச்சொல் புதுப்பி",
    changing: "புதுப்பிக்கிறது...",
    password_placeholder: "கடவுச்சொல் உள்ளிடவும்",
    passwords_no_match: "கடவுச்சொற்கள் பொருந்தவில்லை",
    pwd_weak: "பலவீனம்",
    pwd_fair: "சாதாரணம்",
    pwd_good: "நல்லது",
    pwd_strong: "வலிமையானது",
    two_factor: "இரண்டு-காரணி அங்கீகாரம்",
    two_factor_desc: "உங்கள் கணக்கிற்கு கூடுதல் பாதுகாப்பு சேர்க்கவும்",
    two_fa_enabled: "இரண்டு-காரணி அங்கீகாரம் இயக்கப்பட்டுள்ளது.",
    active_sessions: "செயலில் உள்ள அமர்வுகள்",
    revoke_all: "அனைத்தையும் ரத்துசெய்",
    revoke: "ரத்துசெய்",
    current_session: "தற்போதையது",

    email_notif_group: "மின்னஞ்சல் அறிவிப்புகள்",
    sms_notif_group: "SMS அறிவிப்புகள்",
    inapp_notif_group: "செயலி அறிவிப்புகள்",
    notif_campaign_updates: "பிரச்சார புதுப்பிப்புகள்",
    notif_campaign_desc: "பிரச்சாரங்கள் அனுப்பப்படும்போது",
    notif_weekly_reports: "வாராந்திர அறிக்கைகள்",
    notif_weekly_desc: "ஒவ்வொரு திங்கட்கிழமையும் சுருக்கம்",
    notif_billing_alerts: "வரவு செலவு எச்சரிக்கைகள்",
    notif_billing_desc: "விலைப்பட்டியல் மற்றும் கட்டண சிக்கல்கள்",
    notif_team_activity: "குழு செயல்பாடு",
    notif_team_desc: "குழு உறுப்பினர்கள் செயல்படும்போது",
    notif_otp: "OTP மற்றும் சரிபார்ப்பு",
    notif_otp_desc: "உள்நுழைவு மற்றும் பாதுகாப்பு குறியீடுகள்",
    notif_critical: "முக்கியமான எச்சரிக்கைகள் மட்டும்",
    notif_critical_desc: "கணினி நேரமின்மை அல்லது அவசர சிக்கல்கள்",
    notif_campaign_status: "பிரச்சார நிலை",
    notif_campaign_status_desc: "அனுப்புவதன் முன்னேற்றம்",
    notif_team_updates: "குழு புதுப்பிப்புகள்",
    notif_team_updates_desc: "அழைப்புகள் மற்றும் பாத்திர மாற்றங்கள்",
    notif_system_notices: "கணினி அறிவிப்புகள்",
    notif_system_desc: "பராமரிப்பு மற்றும் தள புதுப்பிப்புகள்",
    digest_frequency: "அறிவிப்பு சுருக்கம்",
    freq_real_time: "நிகழ்நேரம்",
    freq_daily: "தினசரி",
    freq_weekly: "வாராந்திரம்",
    freq_never: "ஒருபோதும் இல்லை",

    team_members: "குழு உறுப்பினர்கள்",
    members_in_team: "உறுப்பினர்கள் உங்கள் குழுவில்",
    search_members: "உறுப்பினர்களை தேடு...",
    invite: "அழை",
    invite_title: "குழு உறுப்பினரை அழைக்கவும்",
    invite_email: "மின்னஞ்சல் முகவரி",
    invite_email_placeholder: "colleague@company.com",
    invite_role: "பாத்திரம் ஒதுக்கவும்",
    send_invite: "அழைப்பு அனுப்பு",
    cancel: "ரத்துசெய்",
    total: "மொத்தம்",
    active: "செயலில்",
    inactive: "செயலற்றது",
    pending: "நிலுவையில்",
    member_col: "உறுப்பினர்",
    role_col: "பாத்திரம்",
    status_col: "நிலை",
    joined_col: "சேர்ந்தது",
    actions_col: "செயல்கள்",
    edit_btn: "திருத்து",
    remove_btn: "அகற்று",

    email_provider: "மின்னஞ்சல் வழங்குனர்",
    configuration: "கட்டமைப்பு",
    api_key: "API திறவுகோல்",
    from_email: "அனுப்புநர் மின்னஞ்சல்",
    from_name: "அனுப்புநர் பெயர்",
    reply_to: "பதில் மின்னஞ்சல்",
    daily_limit: "தினசரி அனுப்பல் வரம்பு",
    hourly_limit: "மணிநேர அனுப்பல் வரம்பு",
    test_email: "இணைப்பை சோதி",
    testing: "சோதிக்கிறது...",
    test_success: "இணைப்பு வெற்றிகரமானது!",
    save_config: "கட்டமைப்பை சேமி",

    integrations_active: "ஒருங்கிணைப்புகள் செயலில்",
    integrations_subtitle: "உங்கள் விருப்பமான கருவிகளை இணைக்கவும்",
    connected_badge: "இணைக்கப்பட்டது",
    connect: "இணை",
    disconnect: "துண்டி",

    current_plan: "தற்போதைய திட்டம்",
    renews_on: "ஏப்ரல் 1, 2026 அன்று புதுப்பிக்கப்படும்",
    usage_this_month: "இந்த மாத பயன்பாடு",
    emails_sent: "அனுப்பப்பட்ட மின்னஞ்சல்கள்",
    contacts: "தொடர்புகள்",
    team_members_usage: "குழு உறுப்பினர்கள்",
    used: "பயன்படுத்தப்பட்டது",
    available_plans: "கிடைக்கும் திட்டங்கள்",
    most_popular: "மிகவும் பிரபலமானது",
    current_plan_btn: "தற்போதைய திட்டம்",
    contact_sales: "விற்பனையை தொடர்பு கொள்ளவும்",
    upgrade: "மேம்படுத்து",
    invoice_history: "விலைப்பட்டியல் வரலாறு",
    pdf: "PDF",

    super_admin_only: "சூப்பர் அட்மின் மட்டும்",
    system_warning: "இங்கே செய்யும் மாற்றங்கள் முழு தளத்தையும் பாதிக்கும்.",
    platform_controls: "தள கட்டுப்பாடுகள்",
    platform_config: "தள கட்டமைப்பு",
    on: "இயக்கு",
    off: "நிறுத்து",
    save_system: "கணினி அமைப்புகளை சேமி",
  },


  te: {
    settings_title: "సెట్టింగులు",
    settings_subtitle: "మీ ఖాతా ప్రాధాన్యతలు మరియు కాన్ఫిగరేషన్లు నిర్వహించండి",
    nav_label: "నావిగేషన్",
    your_role: "మీ పాత్ర",

    full_platform_access: "పూర్తి ప్లాట్‌ఫారమ్ యాక్సెస్",
    company_management: "కంపెనీ నిర్వహణ",
    campaign_management: "క్యాంపైన్ నిర్వహణ",
    read_only_access: "చదవడానికి మాత్రమే యాక్సెస్",

    tab_profile: "ప్రొఫైల్",
    tab_security: "భద్రత",
    tab_notifications: "నోటిఫికేషన్లు",
    tab_team: "బృందం",
    tab_email: "ఇమెయిల్ సేవ",
    tab_integrations: "ఇంటిగ్రేషన్లు",
    tab_billing: "బిల్లింగ్",
    tab_system: "సిస్టమ్",

    personal_info: "వ్యక్తిగత సమాచారం",
    full_name: "పూర్తి పేరు",
    email_address: "ఇమెయిల్ చిరునామా",
    company_name: "కంపెనీ పేరు",
    phone_number: "ఫోన్ నంబర్",
    bio_about: "బయో / పరిచయం",
    preferences: "ప్రాధాన్యతలు",
    timezone: "టైమ్‌జోన్",
    language: "భాష",
    save_profile: "ప్రొఫైల్ సేవ్ చేయి",
    saving: "సేవ్ అవుతోంది...",
    saved: "సేవ్ అయింది!",
    name_placeholder: "మీ పూర్తి పేరు",
    email_placeholder: "you@example.com",
    company_placeholder: "మీ కంపెనీ పేరు",
    phone_placeholder: "+91 98765 43210",
    bio_placeholder: "మీ గురించి కొంచెం రాయండి...",

    change_password: "పాస్‌వర్డ్ మార్చు",
    current_password: "ప్రస్తుత పాస్‌వర్డ్",
    new_password: "కొత్త పాస్‌వర్డ్",
    confirm_password: "పాస్‌వర్డ్ నిర్ధారించు",
    change_password_btn: "పాస్‌వర్డ్ అప్‌డేట్ చేయి",
    changing: "అప్‌డేట్ అవుతోంది...",
    password_placeholder: "పాస్‌వర్డ్ నమోదు చేయండి",
    passwords_no_match: "పాస్‌వర్డ్‌లు సరిపోలలేదు",
    pwd_weak: "బలహీనం",
    pwd_fair: "సాధారణం",
    pwd_good: "మంచిది",
    pwd_strong: "బలంగా ఉంది",
    two_factor: "రెండు-కారకాల ప్రమాణీకరణ",
    two_factor_desc: "మీ ఖాతాకు అదనపు భద్రత జోడించండి",
    two_fa_enabled: "రెండు-కారకాల ప్రమాణీకరణ ఎనేబుల్ చేయబడింది.",
    active_sessions: "యాక్టివ్ సెషన్లు",
    revoke_all: "అన్నీ రద్దు చేయి",
    revoke: "రద్దు చేయి",
    current_session: "ప్రస్తుతం",

    email_notif_group: "ఇమెయిల్ నోటిఫికేషన్లు",
    sms_notif_group: "SMS నోటిఫికేషన్లు",
    inapp_notif_group: "యాప్ నోటిఫికేషన్లు",
    notif_campaign_updates: "క్యాంపైన్ అప్‌డేట్‌లు",
    notif_campaign_desc: "క్యాంపైన్‌లు పంపబడినప్పుడు",
    notif_weekly_reports: "వారాంతపు నివేదికలు",
    notif_weekly_desc: "ప్రతి సోమవారం పనితీరు సారాంశం",
    notif_billing_alerts: "బిల్లింగ్ హెచ్చరికలు",
    notif_billing_desc: "ఇన్‌వాయిస్‌లు మరియు చెల్లింపు సమస్యలు",
    notif_team_activity: "బృంద కార్యకలాపాలు",
    notif_team_desc: "బృంద సభ్యులు చర్య తీసుకున్నప్పుడు",
    notif_otp: "OTP మరియు ధృవీకరణ",
    notif_otp_desc: "లాగిన్ మరియు భద్రతా కోడ్‌లు",
    notif_critical: "క్రిటికల్ అలెర్ట్‌లు మాత్రమే",
    notif_critical_desc: "సిస్టమ్ అందుబాటులో లేకపోవడం",
    notif_campaign_status: "క్యాంపైన్ స్థితి",
    notif_campaign_status_desc: "పంపే పురోగతి",
    notif_team_updates: "బృంద అప్‌డేట్‌లు",
    notif_team_updates_desc: "ఆహ్వానాలు మరియు పాత్ర మార్పులు",
    notif_system_notices: "సిస్టమ్ నోటీసులు",
    notif_system_desc: "నిర్వహణ మరియు ప్లాట్‌ఫారమ్ అప్‌డేట్‌లు",
    digest_frequency: "నోటిఫికేషన్ డైజెస్ట్",
    freq_real_time: "రియల్-టైమ్",
    freq_daily: "రోజువారీ",
    freq_weekly: "వారాంతపు",
    freq_never: "ఎప్పుడూ వద్దు",

    team_members: "బృంద సభ్యులు",
    members_in_team: "మీ బృందంలో సభ్యులు",
    search_members: "సభ్యులను వెతకండి...",
    invite: "ఆహ్వానించు",
    invite_title: "బృంద సభ్యుడిని ఆహ్వానించు",
    invite_email: "ఇమెయిల్ చిరునామా",
    invite_email_placeholder: "colleague@company.com",
    invite_role: "పాత్ర నిర్ణయించు",
    send_invite: "ఆహ్వానం పంపు",
    cancel: "రద్దు చేయి",
    total: "మొత్తం",
    active: "యాక్టివ్",
    inactive: "నిష్క్రియంగా ఉంది",
    pending: "పెండింగ్",
    member_col: "సభ్యుడు",
    role_col: "పాత్ర",
    status_col: "స్థితి",
    joined_col: "చేరారు",
    actions_col: "చర్యలు",
    edit_btn: "సవరించు",
    remove_btn: "తొలగించు",

    email_provider: "ఇమెయిల్ ప్రొవైడర్",
    configuration: "కాన్ఫిగరేషన్",
    api_key: "API కీ",
    from_email: "పంపినవారి ఇమెయిల్",
    from_name: "పంపినవారి పేరు",
    reply_to: "రిప్లై-టు ఇమెయిల్",
    daily_limit: "రోజువారీ పంపే పరిమితి",
    hourly_limit: "గంటవారీ పంపే పరిమితి",
    test_email: "కనెక్షన్ పరీక్షించు",
    testing: "పరీక్షిస్తోంది...",
    test_success: "కనెక్షన్ విజయవంతమైంది!",
    save_config: "కాన్ఫిగరేషన్ సేవ్ చేయి",

    integrations_active: "ఇంటిగ్రేషన్లు యాక్టివ్",
    integrations_subtitle: "మీకు నచ్చిన టూల్స్ కనెక్ట్ చేయండి",
    connected_badge: "కనెక్ట్ అయింది",
    connect: "కనెక్ట్ చేయి",
    disconnect: "డిస్‌కనెక్ట్ చేయి",

    current_plan: "ప్రస్తుత ప్లాన్",
    renews_on: "ఏప్రిల్ 1, 2026న పునర్నవీకరించబడుతుంది",
    usage_this_month: "ఈ నెల వాడకం",
    emails_sent: "పంపిన ఇమెయిల్లు",
    contacts: "సంప్రదింపులు",
    team_members_usage: "బృంద సభ్యులు",
    used: "వాడబడింది",
    available_plans: "అందుబాటులో ఉన్న ప్లాన్లు",
    most_popular: "అత్యంత ప్రజాదరణ పొందినది",
    current_plan_btn: "ప్రస్తుత ప్లాన్",
    contact_sales: "సేల్స్‌ని సంప్రదించు",
    upgrade: "అప్‌గ్రేడ్ చేయి",
    invoice_history: "ఇన్‌వాయిస్ చరిత్ర",
    pdf: "PDF",

    super_admin_only: "సూపర్ అడ్మిన్ మాత్రమే",
    system_warning: "ఇక్కడ చేసే మార్పులు మొత్తం ప్లాట్‌ఫారమ్‌ను ప్రభావితం చేస్తాయి.",
    platform_controls: "ప్లాట్‌ఫారమ్ నియంత్రణలు",
    platform_config: "ప్లాట్‌ఫారమ్ కాన్ఫిగరేషన్",
    on: "ఆన్",
    off: "ఆఫ్",
    save_system: "సిస్టమ్ సెట్టింగులు సేవ్ చేయి",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  const t = (key) => {
    return translations[lang]?.[key] ?? translations["en"]?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ t, lang, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}

export default LanguageContext;