// src/pages/admin/Languagecontext.jsx
import { createContext, useContext, useState } from "react";

// ─── All Translations ──────────────────────────────────────────────────────
const T = {
  en: {
    // Nav
    group_main: "Main", group_management: "Management", group_finance: "Finance",
    group_config: "Configuration", group_analytics: "Analytics", group_system: "System",
    dashboard: "Dashboard", user_management: "User Management", campaigns: "Campaigns",
    subscription_plans: "Subscription Plans", billing_payments: "Billing & Payments",
    email_config: "Email Service Config", global_analytics: "Global Analytics",
    system_settings: "System Settings", audit_logs: "Audit Logs",
    profile: "My Profile", settings: "Settings", logout: "Logout",
    welcome_back: "Welcome back", search: "Search...",

    // Settings page
    settings_title: "Settings",
    settings_subtitle: "Manage your account, team, and platform preferences",
    nav_label: "Navigation",
    your_role: "Your Role",
    full_platform_access: "Full platform access",
    company_management: "Company management",
    campaign_management: "Campaign management",
    read_only_access: "Read-only access",

    // Tabs
    tab_profile: "Profile",
    tab_security: "Security",
    tab_notifications: "Notifications",
    tab_team: "Team Members",
    tab_email: "Email Service",
    tab_integrations: "Integrations",
    tab_billing: "Billing & Plans",
    tab_system: "System Settings",

    // Profile Tab
    save_profile: "Save Profile",
    saving: "Saving...",
    saved: "Saved!",
    personal_info: "Personal Information",
    full_name: "Full Name",
    email_address: "Email Address",
    company_name: "Company Name",
    phone_number: "Phone Number",
    bio_about: "Bio / About",
    bio_placeholder: "Write a short bio about yourself...",
    name_placeholder: "Enter your full name",
    email_placeholder: "your@email.com",
    company_placeholder: "Your company name",
    phone_placeholder: "+91 98765 43210",
    preferences: "Preferences",
    timezone: "Timezone",
    language: "Language",

    // Security Tab
    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    password_placeholder: "••••••••",
    passwords_no_match: "Passwords do not match",
    changing: "Changing...",
    change_password_btn: "🔑 Change Password",
    two_factor: "Two-Factor Authentication",
    two_factor_desc: "Add an extra layer of security to your account using TOTP or SMS OTP.",
    two_fa_enabled: "✅ 2FA is enabled. Your account is more secure.",
    active_sessions: "Active Sessions",
    revoke_all: "Revoke All Others",
    revoke: "Revoke",
    current_session: "CURRENT",
    pwd_weak: "Weak", pwd_fair: "Fair", pwd_good: "Good", pwd_strong: "Strong",

    // Notifications Tab
    email_notif_group: "Email Notifications",
    sms_notif_group: "SMS Notifications",
    inapp_notif_group: "In-App Notifications",
    notif_campaign_updates: "Campaign updates",
    notif_campaign_desc: "When campaigns start, finish, or fail",
    notif_weekly_reports: "Weekly reports",
    notif_weekly_desc: "Performance summaries every Monday",
    notif_billing_alerts: "Billing alerts",
    notif_billing_desc: "Invoices and payment reminders",
    notif_team_activity: "Team activity",
    notif_team_desc: "When team members are added or edited",
    notif_otp: "OTP & verification",
    notif_otp_desc: "Login and action verification codes",
    notif_critical: "Critical alerts",
    notif_critical_desc: "System outages and urgent warnings",
    notif_campaign_status: "Campaign status",
    notif_campaign_status_desc: "Real-time campaign progress",
    notif_team_updates: "Team updates",
    notif_team_updates_desc: "New members and role changes",
    notif_system_notices: "System notices",
    notif_system_desc: "Maintenance and downtime alerts",
    digest_frequency: "Email Digest Frequency",
    freq_real_time: "real-time",
    freq_daily: "daily",
    freq_weekly: "weekly",
    freq_never: "never",

    // Team Tab
    team_members: "Team Members",
    members_in_team: "members in your team",
    search_members: "Search members...",
    invite: "+ Invite",
    total: "Total", active: "Active", inactive: "Inactive", pending: "Pending",
    member_col: "Member", role_col: "Role", status_col: "Status",
    joined_col: "Joined", actions_col: "Actions",
    edit_btn: "Edit", remove_btn: "Remove",
    invite_title: "Invite Team Member",
    invite_email: "Email Address",
    invite_email_placeholder: "colleague@company.com",
    invite_role: "Role",
    cancel: "Cancel",
    send_invite: "Send Invite",

    // Email Service Tab
    email_provider: "Email Provider",
    configuration: "Configuration",
    api_key: "API Key / Secret",
    from_email: "From Email",
    from_name: "From Name",
    reply_to: "Reply-To Email",
    daily_limit: "Daily Send Limit",
    hourly_limit: "Hourly Limit",
    test_email: "🧪 Send Test Email",
    testing: "Testing...",
    save_config: "💾 Save Configuration",
    test_success: "Test email sent successfully! Check your inbox.",
    test_fail: "Failed to send test email. Check your configuration.",

    // Integrations Tab
    integrations_active: "integrations active",
    integrations_subtitle: "Connect your favorite tools to supercharge MailDoll",
    connect: "Connect",
    disconnect: "Disconnect",
    connected_badge: "CONNECTED",

    // Billing Tab
    current_plan: "Current Plan",
    renews_on: "Renews on April 1, 2026 · ₹2,999/month",
    usage_this_month: "Usage This Month",
    emails_sent: "Emails Sent",
    contacts: "Contacts",
    team_members_usage: "Team Members",
    used: "used",
    available_plans: "Available Plans",
    most_popular: "MOST POPULAR",
    current_plan_btn: "✓ Current Plan",
    contact_sales: "Contact Sales",
    upgrade: "Upgrade",
    invoice_history: "Invoice History",
    pdf: "PDF",

    // System Tab
    super_admin_only: "Super Admin Only",
    system_warning: "Changes here affect the entire platform. Proceed with caution.",
    platform_controls: "Platform Controls",
    platform_config: "Platform Configuration",
    on: "ON", off: "OFF",
    save_system: "💾 Save System Settings",

    // Admin profile
    my_profile: "My Profile", joined: "Joined March 2026", full_name_lbl: "Full Name",
    role_lbl: "Role", super_admin: "Super Admin", account_info: "Account Info",
    activity: "Activity", edit_profile: "Edit Profile", save: "Save",
    logged_in: "Logged in", just_now: "Just now",
    sent_emails_act: "Sent 24 emails", created_campaign: "Created campaign",
    updated_settings: "Updated settings", coming_soon: "This page is coming soon.",
  },

  mr: {
    group_main: "मुख्य", group_management: "व्यवस्थापन", group_finance: "वित्त",
    group_config: "कॉन्फिगरेशन", group_analytics: "विश्लेषण", group_system: "सिस्टम",
    dashboard: "डॅशबोर्ड", user_management: "यूजर व्यवस्थापन", campaigns: "मोहिमा",
    subscription_plans: "सदस्यता योजना", billing_payments: "बिलिंग आणि पेमेंट",
    email_config: "ईमेल सेवा सेटअप", global_analytics: "ग्लोबल विश्लेषण",
    system_settings: "सिस्टम सेटिंग्ज", audit_logs: "ऑडिट नोंदी",
    profile: "माझी प्रोफाइल", settings: "सेटिंग्ज", logout: "लॉगआउट",
    welcome_back: "परत स्वागत आहे", search: "शोधा...",

    settings_title: "सेटिंग्ज",
    settings_subtitle: "तुमचे खाते, टीम आणि प्लॅटफॉर्म प्राधान्ये व्यवस्थापित करा",
    nav_label: "नेव्हिगेशन",
    your_role: "तुमची भूमिका",
    full_platform_access: "संपूर्ण प्लॅटफॉर्म access",
    company_management: "कंपनी व्यवस्थापन",
    campaign_management: "मोहीम व्यवस्थापन",
    read_only_access: "फक्त वाचण्याचा access",

    tab_profile: "प्रोफाइल",
    tab_security: "सुरक्षा",
    tab_notifications: "सूचना",
    tab_team: "टीम सदस्य",
    tab_email: "ईमेल सेवा",
    tab_integrations: "इंटिग्रेशन",
    tab_billing: "बिलिंग आणि योजना",
    tab_system: "सिस्टम सेटिंग्ज",

    save_profile: "प्रोफाइल जतन करा",
    saving: "जतन होत आहे...",
    saved: "जतन झाले!",
    personal_info: "वैयक्तिक माहिती",
    full_name: "पूर्ण नाव",
    email_address: "ईमेल पत्ता",
    company_name: "कंपनीचे नाव",
    phone_number: "फोन नंबर",
    bio_about: "बायो / परिचय",
    bio_placeholder: "स्वतःबद्दल थोडक्यात लिहा...",
    name_placeholder: "तुमचे पूर्ण नाव टाका",
    email_placeholder: "तुमचा@ईमेल.com",
    company_placeholder: "तुमच्या कंपनीचे नाव",
    phone_placeholder: "+91 98765 43210",
    preferences: "प्राधान्ये",
    timezone: "टाइमझोन",
    language: "भाषा",

    change_password: "पासवर्ड बदला",
    current_password: "सध्याचा पासवर्ड",
    new_password: "नवीन पासवर्ड",
    confirm_password: "पासवर्ड पुन्हा टाका",
    password_placeholder: "••••••••",
    passwords_no_match: "पासवर्ड जुळत नाहीत",
    changing: "बदलत आहे...",
    change_password_btn: "🔑 पासवर्ड बदला",
    two_factor: "द्वि-स्तरीय प्रमाणीकरण",
    two_factor_desc: "TOTP किंवा SMS OTP वापरून तुमच्या खात्याला अतिरिक्त सुरक्षा द्या.",
    two_fa_enabled: "✅ 2FA सक्रिय आहे. तुमचे खाते अधिक सुरक्षित आहे.",
    active_sessions: "सक्रिय सेशन्स",
    revoke_all: "बाकी सर्व रद्द करा",
    revoke: "रद्द करा",
    current_session: "सध्याचे",
    pwd_weak: "कमकुवत", pwd_fair: "बरा", pwd_good: "चांगला", pwd_strong: "मजबूत",

    email_notif_group: "ईमेल सूचना",
    sms_notif_group: "SMS सूचना",
    inapp_notif_group: "अ‍ॅप अंतर्गत सूचना",
    notif_campaign_updates: "मोहीम अपडेट्स",
    notif_campaign_desc: "मोहीम सुरू, पूर्ण किंवा अयशस्वी झाल्यावर",
    notif_weekly_reports: "साप्ताहिक अहवाल",
    notif_weekly_desc: "दर सोमवारी कामगिरी सारांश",
    notif_billing_alerts: "बिलिंग अलर्ट",
    notif_billing_desc: "बीजक आणि पेमेंट स्मरणपत्रे",
    notif_team_activity: "टीम क्रियाकलाप",
    notif_team_desc: "टीम सदस्य जोडल्यावर किंवा बदलल्यावर",
    notif_otp: "OTP आणि प्रमाणीकरण",
    notif_otp_desc: "लॉगिन आणि क्रिया प्रमाणीकरण कोड",
    notif_critical: "गंभीर अलर्ट",
    notif_critical_desc: "सिस्टम खराबी आणि तातडीच्या सूचना",
    notif_campaign_status: "मोहीम स्थिती",
    notif_campaign_status_desc: "रिअल-टाइम मोहीम प्रगती",
    notif_team_updates: "टीम अपडेट्स",
    notif_team_updates_desc: "नवीन सदस्य आणि भूमिका बदल",
    notif_system_notices: "सिस्टम सूचना",
    notif_system_desc: "देखभाल आणि डाउनटाइम अलर्ट",
    digest_frequency: "ईमेल डायजेस्ट वारंवारता",
    freq_real_time: "तत्काळ",
    freq_daily: "दैनंदिन",
    freq_weekly: "साप्ताहिक",
    freq_never: "कधीच नाही",

    team_members: "टीम सदस्य",
    members_in_team: "सदस्य तुमच्या टीममध्ये",
    search_members: "सदस्य शोधा...",
    invite: "+ आमंत्रित करा",
    total: "एकूण", active: "सक्रिय", inactive: "निष्क्रिय", pending: "प्रलंबित",
    member_col: "सदस्य", role_col: "भूमिका", status_col: "स्थिती",
    joined_col: "सामील", actions_col: "क्रिया",
    edit_btn: "संपादित", remove_btn: "काढून टाका",
    invite_title: "टीम सदस्याला आमंत्रित करा",
    invite_email: "ईमेल पत्ता",
    invite_email_placeholder: "सहकारी@कंपनी.com",
    invite_role: "भूमिका",
    cancel: "रद्द करा",
    send_invite: "आमंत्रण पाठवा",

    email_provider: "ईमेल प्रदाता",
    configuration: "कॉन्फिगरेशन",
    api_key: "API की / सिक्रेट",
    from_email: "प्रेषक ईमेल",
    from_name: "प्रेषकाचे नाव",
    reply_to: "Reply-To ईमेल",
    daily_limit: "दैनंदिन पाठवण्याची मर्यादा",
    hourly_limit: "तासिक मर्यादा",
    test_email: "🧪 चाचणी ईमेल पाठवा",
    testing: "चाचणी होत आहे...",
    save_config: "💾 कॉन्फिगरेशन जतन करा",
    test_success: "चाचणी ईमेल यशस्वीरित्या पाठवला! तुमचा इनबॉक्स तपासा.",
    test_fail: "चाचणी ईमेल पाठवणे अयशस्वी. कॉन्फिगरेशन तपासा.",

    integrations_active: "इंटिग्रेशन सक्रिय",
    integrations_subtitle: "MailDoll अधिक सशक्त करण्यासाठी आवडते tools जोडा",
    connect: "जोडा",
    disconnect: "काढून टाका",
    connected_badge: "जोडलेले",

    current_plan: "सध्याची योजना",
    renews_on: "१ एप्रिल २०२६ रोजी नूतनीकरण · ₹२,९९९/महिना",
    usage_this_month: "या महिन्याचा वापर",
    emails_sent: "ईमेल पाठवले",
    contacts: "संपर्क",
    team_members_usage: "टीम सदस्य",
    used: "वापरले",
    available_plans: "उपलब्ध योजना",
    most_popular: "सर्वाधिक लोकप्रिय",
    current_plan_btn: "✓ सध्याची योजना",
    contact_sales: "विक्री संपर्क करा",
    upgrade: "अपग्रेड करा",
    invoice_history: "बीजक इतिहास",
    pdf: "PDF",

    super_admin_only: "फक्त सुपर अ‍ॅडमिन",
    system_warning: "येथील बदल संपूर्ण प्लॅटफॉर्मवर परिणाम करतात. सावधगिरीने पुढे जा.",
    platform_controls: "प्लॅटफॉर्म नियंत्रणे",
    platform_config: "प्लॅटफॉर्म कॉन्फिगरेशन",
    on: "चालू", off: "बंद",
    save_system: "💾 सिस्टम सेटिंग्ज जतन करा",

    my_profile: "माझी प्रोफाइल", joined: "मार्च २०२६ रोजी सामील झाले",
    full_name_lbl: "पूर्ण नाव", role_lbl: "भूमिका", super_admin: "सुपर अ‍ॅडमिन",
    account_info: "खाते माहिती", activity: "क्रियाकलाप",
    edit_profile: "प्रोफाइल संपादित करा", save: "जतन करा",
    logged_in: "लॉगिन केले", just_now: "आत्ताच",
    sent_emails_act: "२४ ईमेल पाठवले", created_campaign: "मोहीम तयार केली",
    updated_settings: "सेटिंग्ज अपडेट केल्या", coming_soon: "हे पेज लवकरच येईल.",
  },

  hi: {
    group_main: "मुख्य", group_management: "प्रबंधन", group_finance: "वित्त",
    group_config: "कॉन्फिगरेशन", group_analytics: "विश्लेषण", group_system: "सिस्टम",
    dashboard: "डैशबोर्ड", user_management: "उपयोगकर्ता प्रबंधन", campaigns: "अभियान",
    subscription_plans: "सदस्यता योजनाएं", billing_payments: "बिलिंग और भुगतान",
    email_config: "ईमेल सेवा कॉन्फिग", global_analytics: "ग्लोबल विश्लेषण",
    system_settings: "सिस्टम सेटिंग्स", audit_logs: "ऑडिट लॉग्स",
    profile: "मेरी प्रोफ़ाइल", settings: "सेटिंग्स", logout: "लॉगआउट",
    welcome_back: "वापस स्वागत है", search: "खोजें...",

    settings_title: "सेटिंग्स",
    settings_subtitle: "अपना खाता, टीम और प्लेटफ़ॉर्म प्राथमिकताएं प्रबंधित करें",
    nav_label: "नेविगेशन",
    your_role: "आपकी भूमिका",
    full_platform_access: "पूर्ण प्लेटफ़ॉर्म एक्सेस",
    company_management: "कंपनी प्रबंधन",
    campaign_management: "अभियान प्रबंधन",
    read_only_access: "केवल-पढ़ने की एक्सेस",

    tab_profile: "प्रोफ़ाइल",
    tab_security: "सुरक्षा",
    tab_notifications: "सूचनाएं",
    tab_team: "टीम सदस्य",
    tab_email: "ईमेल सेवा",
    tab_integrations: "इंटीग्रेशन",
    tab_billing: "बिलिंग और योजनाएं",
    tab_system: "सिस्टम सेटिंग्स",

    save_profile: "प्रोफ़ाइल सहेजें",
    saving: "सहेजा जा रहा है...",
    saved: "सहेजा गया!",
    personal_info: "व्यक्तिगत जानकारी",
    full_name: "पूरा नाम",
    email_address: "ईमेल पता",
    company_name: "कंपनी का नाम",
    phone_number: "फ़ोन नंबर",
    bio_about: "बायो / परिचय",
    bio_placeholder: "अपने बारे में संक्षिप्त लिखें...",
    name_placeholder: "अपना पूरा नाम दर्ज करें",
    email_placeholder: "आपका@ईमेल.com",
    company_placeholder: "आपकी कंपनी का नाम",
    phone_placeholder: "+91 98765 43210",
    preferences: "प्राथमिकताएं",
    timezone: "टाइमज़ोन",
    language: "भाषा",

    change_password: "पासवर्ड बदलें",
    current_password: "वर्तमान पासवर्ड",
    new_password: "नया पासवर्ड",
    confirm_password: "पासवर्ड की पुष्टि करें",
    password_placeholder: "••••••••",
    passwords_no_match: "पासवर्ड मेल नहीं खाते",
    changing: "बदला जा रहा है...",
    change_password_btn: "🔑 पासवर्ड बदलें",
    two_factor: "दो-कारक प्रमाणीकरण",
    two_factor_desc: "TOTP या SMS OTP का उपयोग करके अपने खाते में सुरक्षा की अतिरिक्त परत जोड़ें।",
    two_fa_enabled: "✅ 2FA सक्षम है। आपका खाता अधिक सुरक्षित है।",
    active_sessions: "सक्रिय सत्र",
    revoke_all: "बाकी सभी रद्द करें",
    revoke: "रद्द करें",
    current_session: "वर्तमान",
    pwd_weak: "कमज़ोर", pwd_fair: "ठीक", pwd_good: "अच्छा", pwd_strong: "मज़बूत",

    email_notif_group: "ईमेल सूचनाएं",
    sms_notif_group: "SMS सूचनाएं",
    inapp_notif_group: "इन-ऐप सूचनाएं",
    notif_campaign_updates: "अभियान अपडेट",
    notif_campaign_desc: "जब अभियान शुरू, समाप्त या विफल हों",
    notif_weekly_reports: "साप्ताहिक रिपोर्ट",
    notif_weekly_desc: "हर सोमवार प्रदर्शन सारांश",
    notif_billing_alerts: "बिलिंग अलर्ट",
    notif_billing_desc: "चालान और भुगतान अनुस्मारक",
    notif_team_activity: "टीम गतिविधि",
    notif_team_desc: "जब टीम सदस्य जोड़े या संपादित किए जाएं",
    notif_otp: "OTP और सत्यापन",
    notif_otp_desc: "लॉगिन और कार्य सत्यापन कोड",
    notif_critical: "गंभीर अलर्ट",
    notif_critical_desc: "सिस्टम आउटेज और तत्काल चेतावनियाँ",
    notif_campaign_status: "अभियान स्थिति",
    notif_campaign_status_desc: "रियल-टाइम अभियान प्रगति",
    notif_team_updates: "टीम अपडेट",
    notif_team_updates_desc: "नए सदस्य और भूमिका परिवर्तन",
    notif_system_notices: "सिस्टम सूचनाएं",
    notif_system_desc: "रखरखाव और डाउनटाइम अलर्ट",
    digest_frequency: "ईमेल डाइजेस्ट आवृत्ति",
    freq_real_time: "तत्काल",
    freq_daily: "दैनिक",
    freq_weekly: "साप्ताहिक",
    freq_never: "कभी नहीं",

    team_members: "टीम सदस्य",
    members_in_team: "सदस्य आपकी टीम में",
    search_members: "सदस्य खोजें...",
    invite: "+ आमंत्रित करें",
    total: "कुल", active: "सक्रिय", inactive: "निष्क्रिय", pending: "लंबित",
    member_col: "सदस्य", role_col: "भूमिका", status_col: "स्थिति",
    joined_col: "जुड़े", actions_col: "क्रियाएं",
    edit_btn: "संपादित", remove_btn: "हटाएं",
    invite_title: "टीम सदस्य को आमंत्रित करें",
    invite_email: "ईमेल पता",
    invite_email_placeholder: "सहकर्मी@कंपनी.com",
    invite_role: "भूमिका",
    cancel: "रद्द करें",
    send_invite: "आमंत्रण भेजें",

    email_provider: "ईमेल प्रदाता",
    configuration: "कॉन्फिगरेशन",
    api_key: "API की / सीक्रेट",
    from_email: "प्रेषक ईमेल",
    from_name: "प्रेषक का नाम",
    reply_to: "Reply-To ईमेल",
    daily_limit: "दैनिक भेजने की सीमा",
    hourly_limit: "प्रति घंटा सीमा",
    test_email: "🧪 परीक्षण ईमेल भेजें",
    testing: "परीक्षण हो रहा है...",
    save_config: "💾 कॉन्फिगरेशन सहेजें",
    test_success: "परीक्षण ईमेल सफलतापूर्वक भेजा गया! अपना इनबॉक्स जांचें।",
    test_fail: "परीक्षण ईमेल भेजना विफल। अपना कॉन्फिगरेशन जांचें।",

    integrations_active: "इंटीग्रेशन सक्रिय",
    integrations_subtitle: "MailDoll को सुपरचार्ज करने के लिए अपने पसंदीदा tools कनेक्ट करें",
    connect: "जोड़ें",
    disconnect: "हटाएं",
    connected_badge: "जुड़ा हुआ",

    current_plan: "वर्तमान योजना",
    renews_on: "1 अप्रैल 2026 को नवीनीकृत · ₹2,999/माह",
    usage_this_month: "इस महीने का उपयोग",
    emails_sent: "ईमेल भेजे",
    contacts: "संपर्क",
    team_members_usage: "टीम सदस्य",
    used: "उपयोग",
    available_plans: "उपलब्ध योजनाएं",
    most_popular: "सर्वाधिक लोकप्रिय",
    current_plan_btn: "✓ वर्तमान योजना",
    contact_sales: "बिक्री से संपर्क करें",
    upgrade: "अपग्रेड करें",
    invoice_history: "चालान इतिहास",
    pdf: "PDF",

    super_admin_only: "केवल सुपर एडमिन",
    system_warning: "यहाँ के बदलाव पूरे प्लेटफ़ॉर्म को प्रभावित करते हैं। सावधानी से आगे बढ़ें।",
    platform_controls: "प्लेटफ़ॉर्म नियंत्रण",
    platform_config: "प्लेटफ़ॉर्म कॉन्फिगरेशन",
    on: "चालू", off: "बंद",
    save_system: "💾 सिस्टम सेटिंग्स सहेजें",

    my_profile: "मेरी प्रोफ़ाइल", joined: "मार्च 2026 में जुड़े",
    full_name_lbl: "पूरा नाम", role_lbl: "भूमिका", super_admin: "सुपर एडमिन",
    account_info: "खाता जानकारी", activity: "गतिविधि",
    edit_profile: "प्रोफ़ाइल संपादित करें", save: "सहेजें",
    logged_in: "लॉग इन किया", just_now: "अभी",
    sent_emails_act: "24 ईमेल भेजे", created_campaign: "अभियान बनाया",
    updated_settings: "सेटिंग्स अपडेट की", coming_soon: "यह पेज जल्द आएगा।",
  },

  gu: {
    group_main: "મુખ્ય", group_management: "વ્યવસ્થાપન", group_finance: "નાણાં",
    group_config: "ગોઠવણ", group_analytics: "વિશ્લેષણ", group_system: "સિસ્ટમ",
    dashboard: "ડેશબોર્ડ", user_management: "વપરાશકર્તા વ્યવસ્થાપન", campaigns: "ઝુંબેશ",
    subscription_plans: "સભ્યપદ યોજનાઓ", billing_payments: "બિલિંગ અને ચુકવણી",
    email_config: "ઈ-મેઇલ સેવા ગોઠવણ", global_analytics: "ગ્લોબલ વિશ્લેષણ",
    system_settings: "સિસ્ટમ સેટિંગ્સ", audit_logs: "ઓડિટ નોંધ",
    profile: "મારી પ્રોફાઇલ", settings: "સેટિંગ્સ", logout: "લૉગઆઉટ",
    welcome_back: "પાછા સ્વાગત છે", search: "શોધો...",

    settings_title: "સેટિંગ્સ",
    settings_subtitle: "તમારું ખાતું, ટીમ અને પ્લેટફોર્મ પ્રાધાન્યતા સંચાલિત કરો",
    nav_label: "નેવિગેશન",
    your_role: "તમારી ભૂમિકા",
    full_platform_access: "સંપૂર્ણ પ્લેટફોર્મ ઍક્સેસ",
    company_management: "કંપની વ્યવસ્થાપન",
    campaign_management: "ઝુંબેશ વ્યવસ્થાપન",
    read_only_access: "ફક્ત વાંચવાની ઍક્સેસ",

    tab_profile: "પ્રોફાઇલ",
    tab_security: "સુરક્ષા",
    tab_notifications: "સૂચનાઓ",
    tab_team: "ટીમ સભ્યો",
    tab_email: "ઈ-મેઇલ સેવા",
    tab_integrations: "ઇન્ટિગ્રેશન",
    tab_billing: "બિલિંગ અને યોજનાઓ",
    tab_system: "સિસ્ટમ સેટિંગ્સ",

    save_profile: "પ્રોફાઇલ સાચવો",
    saving: "સાચવાઈ રહ્યું છે...",
    saved: "સાચવ્યું!",
    personal_info: "વ્યક્તિગત માહિતી",
    full_name: "પૂરું નામ",
    email_address: "ઈ-મેઇલ સરનામું",
    company_name: "કંપનીનું નામ",
    phone_number: "ફોન નંબર",
    bio_about: "બાયો / પરિચય",
    bio_placeholder: "તમારા વિશે ટૂંકમાં લખો...",
    name_placeholder: "તમારું પૂરું નામ દાખલ કરો",
    email_placeholder: "તમારો@ઈ-મેઇલ.com",
    company_placeholder: "તમારી કંપનીનું નામ",
    phone_placeholder: "+91 98765 43210",
    preferences: "પ્રાધાન્યતા",
    timezone: "ટાઇમઝોન",
    language: "ભાષા",

    change_password: "પાસવર્ડ બદલો",
    current_password: "વર્તમાન પાસવર્ડ",
    new_password: "નવો પાસવર્ડ",
    confirm_password: "પાસવર્ડ ની પુષ્ટિ કરો",
    password_placeholder: "••••••••",
    passwords_no_match: "પાસવર્ડ મેળ ખાતા નથી",
    changing: "બદલાઈ રહ્યું છે...",
    change_password_btn: "🔑 પાસવર્ડ બદલો",
    two_factor: "દ્વિ-પરિબળ પ્રમાણીકરણ",
    two_factor_desc: "TOTP અથવા SMS OTP વાપરીને તમારા ખાતામાં સુરક્ષાનો વધારાનો સ્તર ઉમેરો.",
    two_fa_enabled: "✅ 2FA સક્ષમ છે. તમારું ખાતું વધુ સુરક્ષિત છે.",
    active_sessions: "સક્રિય સત્રો",
    revoke_all: "બાકી બધા રદ કરો",
    revoke: "રદ કરો",
    current_session: "વર્તમાન",
    pwd_weak: "નબળો", pwd_fair: "ઠીક", pwd_good: "સારો", pwd_strong: "મજબૂત",

    email_notif_group: "ઈ-મેઇલ સૂચનાઓ",
    sms_notif_group: "SMS સૂચનાઓ",
    inapp_notif_group: "ઇન-ઍપ સૂચનાઓ",
    notif_campaign_updates: "ઝુંબેશ અપડેટ",
    notif_campaign_desc: "જ્યારે ઝુંબેશ શરૂ, સમાપ્ત અથવા નિષ્ફળ થાય",
    notif_weekly_reports: "સાપ્તાહિક અહેવાલ",
    notif_weekly_desc: "દર સોમવારે કામગીરી સારાંશ",
    notif_billing_alerts: "બિલિંગ ચેતવણીઓ",
    notif_billing_desc: "ઇન્વૉઇસ અને ચુકવણી રીમાઇન્ડર",
    notif_team_activity: "ટીમ પ્રવૃત્તિ",
    notif_team_desc: "જ્યારે ટીમ સભ્ય ઉમેરાય અથવા સંપાદિત થાય",
    notif_otp: "OTP અને ચકાસણી",
    notif_otp_desc: "લૉગિન અને ક્રિયા ચકાસણી કોડ",
    notif_critical: "ગંભીર ચેતવણીઓ",
    notif_critical_desc: "સિસ્ટમ ઊંધું પડવું અને તાત્કાલિક ચેતવણીઓ",
    notif_campaign_status: "ઝુંબેશ સ્થિતિ",
    notif_campaign_status_desc: "રિઅલ-ટાઇમ ઝુંબેશ પ્રગતિ",
    notif_team_updates: "ટીમ અપડેટ",
    notif_team_updates_desc: "નવા સભ્ય અને ભૂમિકા ફેરફાર",
    notif_system_notices: "સિસ્ટમ સૂચનાઓ",
    notif_system_desc: "જાળવણી અને ડાઉનટાઇમ ચેતવણીઓ",
    digest_frequency: "ઈ-મેઇલ ડાઇજેસ્ટ આવૃત્તિ",
    freq_real_time: "તાત્કાલિક",
    freq_daily: "દૈનિક",
    freq_weekly: "સાપ્તાહિક",
    freq_never: "ક્યારેય નહીં",

    team_members: "ટીમ સભ્યો",
    members_in_team: "સભ્યો તમારી ટીમમાં",
    search_members: "સભ્ય શોધો...",
    invite: "+ આમંત્રિત કરો",
    total: "કુલ", active: "સક્રિય", inactive: "નિષ્ક્રિય", pending: "પ્રલંબિત",
    member_col: "સભ્ય", role_col: "ભૂમિકા", status_col: "સ્થિતિ",
    joined_col: "જોડાયા", actions_col: "ક્રિયાઓ",
    edit_btn: "સંપાદિત", remove_btn: "દૂર કરો",
    invite_title: "ટીમ સભ્યને આમંત્રિત કરો",
    invite_email: "ઈ-મેઇલ સરનામું",
    invite_email_placeholder: "સાથી@કંપની.com",
    invite_role: "ભૂમિકા",
    cancel: "રદ કરો",
    send_invite: "આમંત્રણ મોકલો",

    email_provider: "ઈ-મેઇલ પ્રદાતા",
    configuration: "ગોઠવણ",
    api_key: "API કી / સીક્રેટ",
    from_email: "પ્રેષક ઈ-મેઇલ",
    from_name: "પ્રેષકનું નામ",
    reply_to: "Reply-To ઈ-મેઇલ",
    daily_limit: "દૈનિક મોકલવાની મર્યાદા",
    hourly_limit: "કલાકદીઠ મર્યાદા",
    test_email: "🧪 પરીક્ષણ ઈ-મેઇલ મોકલો",
    testing: "પરીક્ષણ થઈ રહ્યું છે...",
    save_config: "💾 ગોઠવણ સાચવો",
    test_success: "પરીક્ષણ ઈ-મેઇલ સફળતાપૂર્વક મોકલ્યો! તમારો ઇનબૉક્સ તપાસો.",
    test_fail: "પરીક્ષણ ઈ-મેઇલ મોકલવામાં નિષ્ફળ. ગોઠવણ તપાસો.",

    integrations_active: "ઇન્ટિગ્રેશન સક્રિય",
    integrations_subtitle: "MailDoll ને સુપરચાર્જ કરવા માટે પ્રિય tools જોડો",
    connect: "જોડો",
    disconnect: "હટાવો",
    connected_badge: "જોડાયેલ",

    current_plan: "વર્તમાન યોજના",
    renews_on: "1 એપ્રિલ 2026 ના રોજ નવીનીકૃત · ₹2,999/મહિનો",
    usage_this_month: "આ મહિનાનો ઉપયોગ",
    emails_sent: "ઈ-મેઇલ મોકલ્યા",
    contacts: "સંપર્કો",
    team_members_usage: "ટીમ સભ્યો",
    used: "ઉપયોગ",
    available_plans: "ઉપલબ્ધ યોજનાઓ",
    most_popular: "સૌથી લોકપ્રિય",
    current_plan_btn: "✓ વર્તમાન યોજના",
    contact_sales: "વેચાણ સ્ટાફ સંપર્ક",
    upgrade: "અપગ્રેડ કરો",
    invoice_history: "ઇન્વૉઇસ ઇતિહાસ",
    pdf: "PDF",

    super_admin_only: "ફક્ત સુપર એડમિન",
    system_warning: "અહીંના ફેરફારો સમગ્ર પ્લેટફોર્મ પર અસર કરે છે. સાવધાનીથી આગળ વધો.",
    platform_controls: "પ્લેટફોર્મ નિયંત્રણો",
    platform_config: "પ્લેટફોર્મ ગોઠવણ",
    on: "ચાલુ", off: "બંધ",
    save_system: "💾 સિસ્టમ સેટિંગ્સ સાચવો",

    my_profile: "મારી પ્રોફાઇલ", joined: "માર્ચ 2026 માં જોડાયા",
    full_name_lbl: "પૂરું નામ", role_lbl: "ભૂમિકા", super_admin: "સુપર એડમિન",
    account_info: "ખાતા માહિતી", activity: "પ્રવૃત્તિ",
    edit_profile: "પ્રોફાઇલ સંપાદિત કરો", save: "સાચવો",
    logged_in: "લૉગ ઇન થયા", just_now: "હમણાં",
    sent_emails_act: "24 ઈ-મેઇલ મોકલ્યા", created_campaign: "ઝુંબેશ બનાવી",
    updated_settings: "સેટિંગ્સ અપડેટ કર્યા", coming_soon: "આ પૃષ્ઠ ટૂંક સમયમાં આવશે.",
  },

  ta: {
    settings_title: "அமைப்புகள்",
    settings_subtitle: "உங்கள் கணக்கு, குழு மற்றும் தளம் விருப்பங்களை நிர்வகிக்கவும்",
    nav_label: "வழிசெலுத்தல்",
    your_role: "உங்கள் பங்கு",
    tab_profile: "சுயவிவரம்",
    tab_security: "பாதுகாப்பு",
    tab_notifications: "அறிவிப்புகள்",
    tab_team: "குழு உறுப்பினர்கள்",
    tab_email: "மின்னஞ்சல் சேவை",
    tab_integrations: "ஒருங்கிணைப்புகள்",
    tab_billing: "பில்லிங் & திட்டங்கள்",
    tab_system: "கணினி அமைப்புகள்",
    save_profile: "சுயவிவரம் சேமி",
    saving: "சேமிக்கிறது...",
    saved: "சேமிக்கப்பட்டது!",
    personal_info: "தனிப்பட்ட தகவல்",
    full_name: "முழு பெயர்",
    email_address: "மின்னஞ்சல் முகவரி",
    company_name: "நிறுவன பெயர்",
    phone_number: "தொலைபேசி எண்",
    preferences: "விருப்பங்கள்",
    timezone: "நேர மண்டலம்",
    language: "மொழி",
    cancel: "ரத்து செய்",
    save_profile: "சுயவிவரம் சேமி",
    // fallback keys use en
  },

  te: {
    settings_title: "సెట్టింగులు",
    settings_subtitle: "మీ ఖాతా, టీమ్ మరియు ప్లాట్‌ఫారమ్ ప్రాధాన్యతలను నిర్వహించండి",
    nav_label: "నావిగేషన్",
    your_role: "మీ పాత్ర",
    tab_profile: "ప్రొఫైల్",
    tab_security: "భద్రత",
    tab_notifications: "నోటిఫికేషన్లు",
    tab_team: "టీమ్ సభ్యులు",
    tab_email: "ఇమెయిల్ సేవ",
    tab_integrations: "ఇంటిగ్రేషన్లు",
    tab_billing: "బిల్లింగ్ & ప్లాన్లు",
    tab_system: "సిస్టమ్ సెట్టింగులు",
    save_profile: "ప్రొఫైల్ సేవ్ చేయి",
    saving: "సేవ్ అవుతోంది...",
    saved: "సేవ్ అయింది!",
    personal_info: "వ్యక్తిగత సమాచారం",
    full_name: "పూర్తి పేరు",
    email_address: "ఇమెయిల్ చిరునామా",
    company_name: "కంపెనీ పేరు",
    phone_number: "ఫోన్ నంబర్",
    preferences: "ప్రాధాన్యతలు",
    timezone: "టైమ్‌జోన్",
    language: "భాష",
    cancel: "రద్దు చేయి",
  },
};

const LC = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  // fallback: if key not in current lang, use English
  const t = (key) => T[lang]?.[key] ?? T.en?.[key] ?? key;
  return <LC.Provider value={{ lang, setLang, t }}>{children}</LC.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LC);
  if (!ctx) throw new Error("useLanguage must be inside <LanguageProvider>");
  return ctx;
}